version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_databases
    ports:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
