version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_databases
    ports:
      - "3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  backend:
    depends_on:
      - mysql
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
